Try removing empty fields from valuees before updateProjectItemFieldValue
When running the import I am getting:an error:
```
2024-08-09T16:27:38.959Z debug: Response: 200 OK - {"data":{"addProjectV2DraftIssue":{"projectItem":{"id":"PVTI_lADOABJSZ84AmAGazgRtVEU"}}}}
2024-08-09T16:27:38.959Z info: Created project item PVTI_lADOABJSZ84AmAGazgRtVEU based on source project item MDEzOlByb2plY3RWMkl0ZW0zNTA2
2024-08-09T16:27:38.959Z info: Setting field "Status" (1/1) on project item PVTI_lADOABJSZ84AmAGazgRtVEU...
2024-08-09T16:27:38.960Z debug: Request: POST https://api.github.com/graphql -
    mutation updateProjectItemFieldValue($projectId: ID!, $itemId: ID!, $fieldId: ID!, $value: ProjectV2FieldValue!) {
      updateProjectV2ItemFieldValue(input: { projectId: $projectId, itemId: $itemId, fieldId: $fieldId, value: $value }) {
        projectV2Item {
          id
        }
      }
    }

2024-08-09T16:27:39.645Z debug: Response: 200 OK - {"data":{"updateProjectV2ItemFieldValue":null},"errors":[{"path":["updateProjectV2ItemFieldValue"],"locations":[{"line":3,"column":7}],"message":"ProjectV2FieldValue has the wrong arguments"}]}
Request failed due to following response errors:
 - ProjectV2FieldValue has the wrong arguments
GraphqlResponseError: Request failed due to following response errors:
 - ProjectV2FieldValue has the wrong arguments
    at /snapshot/dist/migrate-project.cjs
    at async updateProjectItemFieldValue (/snapshot/dist/migrate-project.cjs)
    at async importProjectItem (/snapshot/dist/migrate-project.cjs)
    at async /snapshot/dist/migrate-project.cjs
    at async _Command.<anonymous> (/snapshot/dist/migrate-project.cjs)
```

Our hackathon project uses a singleSelectOptionId for the item's status field which
seems similar to this issue on the the dotnet graphql client:
https://github.com/octokit/octokit.graphql.net/issues/292

Trying a similar fix here, remove the nulls from the value object before sending
it to github.